export const SET_CURRENT_CATEGORY = 'SET_CURRENT_CATEGORY';
export const SET_ALL_CATEGORIES_REQ = 'SET_ALL_CATEGORIES_REQ';
export const SET_ALL_CATEGORIES_SUCCESS = 'SET_ALL_CATEGORIES_SUCCESS';
export const SET_ALL_CATEGORIES_FAIL = 'SET_ALL_CATEGORIES_FAIL';
